### ISSUE TITLE
Decoración del proyecto

### ISSUE THREAD

**Issue by Amable-Valdes** [Arquisoft/Trivial2b#2]
Hay que "vender" la aplicación. Para la página web necesito el "Verdadero nombre" de la aplicación:

Si quisieramos vender una aplicación no lo llamaríamos Trivial2b... Yo lo llamaría "Supertrivial" o "GreaTTrivial" o algo por el estilo que llamase al consumismo y que se vendiese solo.

¿Alguna idea para un nombre original?

**Comment by JaimeDiazGarcia** [comment]
Aunque tenemos tiempo hasta tenerla terminada, yo dejo caer algunas: Trivioleta, Trevial, triviaLive

**Comment by marcosgarciagarcia202** [comment]
Yo creo que debería ser un nombre que describa la aplicación pero a la vez nos describa a nosotros como grupo o alguna característica nuestra para hacerlo más personal. Algo que proponer en este sentido?

**Comment by BorjaCM** [comment]
Yo acabo de subir al portada, nombre en esta al proyecto como Ovitrial, una mezcla entre Oviedo y trivial.
pero acabo  de darme cuenta que la mitad de la gente no sera de Oviedo, así que mejor cambiarlo creo yo

**Comment by carlosord** [comment]
Eso de OviTrial suena mas bien a una prueba de deportes en Oviedo, se podria poner un nombre que relaccionase la universidad con el juego, algo en plan Trivial-EII pero mas currado.

**Comment by joseacabaneros** [comment]
A mi OviTrial, me gusta. Es cierto que con ese nombre tiene mas pinta de un juego de preguntas de Oviedo. Por lo demas, perfecto.

**Comment by Amable-Valdes** [comment]
Por votación ha ganado Treevial y pondremos arboles y manzanas.
Me gusta el nombre :)
